### ISSUE TITLE
App crash in release mode when using 'View.propTypes.style' 

### ISSUE THREAD

**Issue by PaulsBecks** [MichaelCereda/react-native-form-generator#131]
This is related to an issue https://github.com/facebook/react-native/issues/16542

As a user has pointed out: 

> View.propTypes.style isn't valid and printed a deprecation message for several releases before it was removed. Use ViewPropTypes.style instead.

**Comment by PaulsBecks** [comment]
Should be solved by #132

**Comment by Asinox** [comment]
Well, i think this issue is still there... Im facing it right now...

**Comment by syky27** [comment]
@Asinox  me too
